# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_start_delay_0/design_1_xlslice_start_delay_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_start_delay_0 || ORIG_REF_NAME==design_1_xlslice_start_delay_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_fire_0/design_1_xlslice_fire_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_fire_0 || ORIG_REF_NAME==design_1_xlslice_fire_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_controller_0_0/design_1_signal_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_signal_controller_0_0 || ORIG_REF_NAME==design_1_signal_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Pwm_0_2/design_1_Pwm_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Pwm_0_2 || ORIG_REF_NAME==design_1_Pwm_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_invert_top_0_0/design_1_invert_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_invert_top_0_0 || ORIG_REF_NAME==design_1_invert_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_band_0/design_1_axi_gpio_band_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_band_0 || ORIG_REF_NAME==design_1_axi_gpio_band_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_band_1/design_1_axi_gpio_band_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_band_1 || ORIG_REF_NAME==design_1_axi_gpio_band_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_start_delay_0/design_1_axi_gpio_start_delay_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_start_delay_0 || ORIG_REF_NAME==design_1_axi_gpio_start_delay_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_start_delay_1/design_1_axi_gpio_start_delay_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_start_delay_1 || ORIG_REF_NAME==design_1_axi_gpio_start_delay_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_5 || ORIG_REF_NAME==design_1_auto_cc_5} -quiet] -quiet

# XDC: c:/Users/Jeppe/Vivado_projects/pwm_pulser5/pwm_ultrasound_pulser/pwm_ultrasound_pulser.gen/sources_1/bd/design_1/design_1_ooc.xdc
