set_property IOSTANDARD LVCMOS33 [get_ports PULSE]
set_property IOSTANDARD LVCMOS33 [get_ports PWM]
set_property IOSTANDARD LVCMOS33 [get_ports PWMN]
set_property IOSTANDARD LVCMOS33 [get_ports GATE]
set_property IOSTANDARD LVCMOS33 [get_ports PRF]
set_property PACKAGE_PIN Y16 [get_ports PULSE]
set_property PACKAGE_PIN Y18 [get_ports PWM]
set_property PACKAGE_PIN Y19 [get_ports PWMN]
set_property PACKAGE_PIN Y17 [get_ports GATE]
set_property PACKAGE_PIN U18 [get_ports PRF]

set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN R14 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN P14 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN N16 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN M14 [get_ports {LEDs[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN U19 [get_ports CLK]
